<?php

/**
 * Created by PhpStorm.
 * User: admin
 * Date: 7/23/2017
 * Time: 6:44 PM
 */
require 'Connection.php';
class DataFile extends Connection
{
    function __construct()
    {
        parent::__construct();
    }
    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    function Products($id,$name,$image,$price)
    {

        $upload_img = $this->cwUpload($image,'',TRUE,'pics/','270','250');

         $str = "insert into products(catid,name,image,price) 
                                values( '$id',' $name','". $image['name']."',' $price')";
        $query = mysqli_query($this->db,$str);
        if($query)
        {
            return true;
        }
        else
        {
            echo mysqli_error($this->db);
        }
    }

    function cwUpload($field_name, $file_name = '', $thumb = FALSE, $thumb_folder = '', $thumb_width = '', $thumb_height = ''){
        //folder path setup

        $target_path = '';
        $thumb_path = $thumb_folder;

        //file name setup
        $filename_err = explode(".",$field_name['name']);
        $filename_err_count = count($filename_err);

        $file_ext = $filename_err[$filename_err_count-1];
        if($file_name != '')
        {
            $fileName = "../pics/".$field_name['name'];
        }
        else
        {
            $fileName = $field_name['name'];
        }

        //upload image path
        $upload_image = "./pics/".$target_path.basename($fileName);

        //upload image
        if(move_uploaded_file($field_name['tmp_name'],$upload_image))
        {
            //thumbnail creation
            if($thumb == TRUE)
            {
                $thumbnail = $thumb_path.$fileName;
                list($width,$height) = getimagesize($upload_image);
                $thumb_create = imagecreatetruecolor($thumb_width,$thumb_height);
                switch($file_ext){
                    case 'jpg':
                        $source = imagecreatefromjpeg($upload_image);
                        break;
                    case 'jpeg':
                        $source = imagecreatefromjpeg($upload_image);
                        break;
                    case 'png':
                        $source = imagecreatefrompng($upload_image);
                        break;
                    case 'gif':
                        $source = imagecreatefromgif($upload_image);
                        break;
                    default:
                        $source = imagecreatefromjpeg($upload_image);
                }
                imagecopyresized($thumb_create,$source,0,0,0,0,$thumb_width,$thumb_height,$width,$height);
                switch($file_ext){
                    case 'jpg' || 'jpeg':
                        imagejpeg($thumb_create,$thumbnail,100);
                        break;
                    case 'png':
                        imagepng($thumb_create,$thumbnail,100);
                        break;
                    case 'gif':
                        imagegif($thumb_create,$thumbnail,100);
                        break;
                    default:
                        imagejpeg($thumb_create,$thumbnail,100);
                }
            }

            return $fileName;
        }
        else
        {
            return false;
        }
    }

    function getData()
    {
        $data = mysqli_query($this->db,"select category.category, category.subcat,products.* from products INNER JOIN category ON products.catid=category.id");
        if (mysqli_num_rows($data)>0){
            $menu='';
            while ($row = mysqli_fetch_array($data))
            {
                $menu .= "<tr>";
                $menu .= "<td>".$row[0]."</td>";
                $menu .= "<td>".$row[1]."</td>";
                $menu .= "<td>".$row[4]."</td>";
                $menu .= "<td><img src='pics/$row[5]' style='width: 150px;'></td>";
                $menu .= "<td> Rs ".$row[6]."</td>";
                $menu .= "<td><a href='home.php?id=$row[2]&dd=$row[5]'>Delete</a> </td>";
            }
            return $menu;
        }
        else
        {
            echo mysqli_error($this->db);
            return null;
        }
    }

    function getContact()
    {
        $data = mysqli_query($this->db,"select * from contact");
        if (mysqli_num_rows($data)>0){
            $menu='';
            while ($row = mysqli_fetch_array($data))
            {
                $menu .= "<tr>";
                $menu .= "<td>".$row[1]."</td>";
                $menu .= "<td>".$row[2]."</td>";
                $menu .= "<td>".$row[3]."</td>";
                $menu .= "<td><a href='contact.php?id=$row[0]'>Delete</a> </td>";
                $menu .= "</tr>";
            }
            return $menu;
        }
        else
        {
            echo mysqli_error($this->db);
            return null;
        }
    }

    function getSubscribe()
    {
        $data = mysqli_query($this->db,"select * from subscribe");
        if (mysqli_num_rows($data)>0){
            $menu='';
            while ($row = mysqli_fetch_array($data))
            {
                $menu .= "<tr>";
                $menu .= "<td>".$row[1]."</td>";
                $menu .= "<td><a href='subscribe.php?id=$row[0]'>Delete</a> </td>";
                $menu .= "</tr>";
            }
            return $menu;
        }
        else
        {
            echo mysqli_error($this->db);
            return null;
        }
    }

    function getBooking()
    {
        $data = mysqli_query($this->db,"select *
        from products INNER JOIN booking ON booking
        .prod_id=products.id INNER JOIN register ON booking.user_id=register.id");
        if (mysqli_num_rows($data)>0){
            $menu='';
            while ($row = mysqli_fetch_array($data))
            {
                /*echo "<pre>";
                print_r($row);
                die();*/
                $menu .= "<tr>";
                $menu .= "<td>".$row[10]."</td>";
                $menu .= "<td>".$row[11]."</td>";
                $menu .= "<td>".$row[2]."</td>";
                $menu .= "<td>".$row[4]."</td>";
                $menu .= "<td>".$row[12]."</td>";
                $menu .= "<td>".$row[8]."</td>";
                $menu .= "<td><a href='bookings.php?id=$row[5]'>Delete</a> </td>";
                $menu .= "</tr>";
            }
            return $menu;
        }
        else
        {
            echo mysqli_error($this->db);
            return null;
        }
    }

}