<?php

/**
 * Created by PhpStorm.
 * User: admin
 * Date: 7/23/2017
 * Time: 12:43 PM
 */
require 'Connection.php';
require 'Sessions.php';
class Login extends Connection
{

    function __construct()
    {
        parent::__construct();
    }
    function __destruct()
    {
        parent::__destruct(); // TODO: Change the autogenerated stub
    }

    function Login($email,$pass)
    {
        $em = $this->test_Input($email);
        $pa = $this->test_Input($pass);
        $query = mysqli_query($this->db,"select * from admin where email='$em' and pass='$pa' ");
        if (mysqli_num_rows($query)>0){
            $row = mysqli_fetch_array($query);
            $obj = new Sessions();
            $obj->set($em,$row[0]);
            return true;
        }
        else{
            return false;
        }
    }
}